## TODO: wtf
###
GET http://localhost:5000/api/person/6/relatives
accept: application/json

###
GET http://localhost:5000/api/tree

###
GET http://localhost:5000/api/person


###

POST http://localhost:5000/api/person
accept: application/json
content-type: application/json

{
 "gender": 0,
 "name": "hello",
 "birthDate": "2000-01-01T00:00:00Z"
}


###

POST http://localhost:5000/api/union
accept: application/json
content-type: application/json

{
 "partner": [4, 5],
 "children": [6, 7]
}

